package Project.Game.Resource;

/**
 * Generates Resources and passes to a Pool
 */
public final class ResourceGenerator {

    private ResourcePool pool;

    private int resourcePerTick;

    public ResourceGenerator(ResourcePool pool, int resourcePerTick) {
        this.pool = pool;
        this.resourcePerTick = (resourcePerTick <= 0) ? 1 : resourcePerTick;
    }

    public int getResourcePerTick() {
        return resourcePerTick;
    }

    /**
     * Stops the pool receiving resource from this stream
     */
    public void deRegister() {
        pool.deRegister(this);
    }

    /**
     * De-registering when finalised, to stop too much resource generated by bad code
     *
     * @throws Throwable
     */
    @Override
    protected void finalize() throws Throwable {
        super.finalize();
        deRegister();
    }
}
